[project]
name = "backtrader_alor"
dependencies = [
    "alor @ git+https://github.com/cianoid/alor@2024.01.17",
    "backtrader==1.9.78.123"
]
description = "Провайдер для автоторговли в BackTrader из Alor Open API "
readme = "README.md"
version = "2024.01.17"
