[project]
name = "backtrader-alor"
dynamic = ["version"]
dependencies = [
    "alor @ git+https://github.com/cianoid/alor@30aac8c1b0536fa9be3f4cdaff75679bfd101348",
    "backtrader==1.9.78.123"
]
description = "Провайдер для автоторговли в BackTrader из Alor Open API "
readme = "README.md"
